# Generated by Django 2.2.4 on 2019-09-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190906_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plan',
            name='full_description',
            field=models.TextField(max_length=3000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateField(default='Unknown', null=True, verbose_name='Дата выполнения'),
        ),
    ]
